### ISSUE TITLE
Native build fails on `psycopg2`, `pg_config` executable not found

### ISSUE THREAD

**Issue by rgstephens** [khalo-sa/rasa-apple-silicon#1]
Native build is failing on `psycopg2` but docker build works. Something related to my conda environment?

```
Collecting psycopg2-binary<2.10.0,>=2.8.2
  Downloading psycopg2-binary-2.9.3.tar.gz (380 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading psycopg2-binary-2.9.2.tar.gz (380 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading psycopg2-binary-2.9.1.tar.gz (380 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Downloading psycopg2-binary-2.9.tar.gz (379 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Using cached psycopg2-binary-2.8.6.tar.gz (384 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Using cached psycopg2-binary-2.8.5.tar.gz (381 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Using cached psycopg2-binary-2.8.4.tar.gz (378 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Using cached psycopg2-binary-2.8.3.tar.gz (378 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  Using cached psycopg2-binary-2.8.2.tar.gz (369 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: /Users/greg/miniforge3/envs/rasa-3.0.4/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-install-1_dmyiuc/psycopg2-binary_d78ec9ab2f7a4dfca71b3ce38aad1dc2/setup.py'"'"'; __file__='"'"'/private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-install-1_dmyiuc/psycopg2-binary_d78ec9ab2f7a4dfca71b3ce38aad1dc2/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4
       cwd: /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-install-1_dmyiuc/psycopg2-binary_d78ec9ab2f7a4dfca71b3ce38aad1dc2/
  Complete output (23 lines):
  running egg_info
  creating /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4/psycopg2_binary.egg-info
  writing /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4/psycopg2_binary.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4/psycopg2_binary.egg-info/dependency_links.txt
  writing top-level names to /private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4/psycopg2_binary.egg-info/top_level.txt
  writing manifest file '/private/var/folders/kj/p2z7dtw53_z4rlt3v7r190k40000gq/T/pip-pip-egg-info-y2jeflk4/psycopg2_binary.egg-info/SOURCES.txt'
  
  Error: pg_config executable not found.
  
  pg_config is required to build psycopg2 from source.  Please add the directory
  containing pg_config to the $PATH or specify the full executable path with the
  option:
  
      python setup.py build_ext --pg-config /path/to/pg_config build ...
  
  or with the pg_config option in 'setup.cfg'.
  
  If you prefer to avoid building psycopg2 from source, please install the PyPI
  'psycopg2-binary' package instead.
  
  For further information please check the 'doc/src/install.rst' file (also at
  <https://www.psycopg.org/docs/install.html>).
```

**Comment by adinutzyc21** [comment]
I got that issue too but then realized I missed the install of mambaforge. Seems to be working for me now

**Comment by rgstephens** [comment]
Still not working for me.

**Comment by khalo-sa** [comment]
Hi @rgstephens , I never faced your issue, but this could be since I have postgresql installed via homebrew on my system, which some users suggest as a solution to a problem looking similar to yours: https://stackoverflow.com/a/24645416

However, I tinkered a little bit with the requirements of the native installation, and hope that `postgresql` is no longer required to be on the system. I also bumped the Rasa version to 3.0.5. 

Can you pull my changes, and report back?

**Comment by rgstephens** [comment]
Thanks, I think it's really close.

```sh
Traceback (most recent call last):
  File "/Users/greg/miniconda3/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/greg/miniconda3/lib/python3.7/site-packages/rasa/__main__.py", line 120, in main
    rasa.telemetry.initialize_error_reporting()
  File "/Users/greg/miniconda3/lib/python3.7/site-packages/rasa/telemetry.py", line 239, in decorated
    return f(*args, **kwargs)
  File "/Users/greg/miniconda3/lib/python3.7/site-packages/rasa/telemetry.py", line 659, in initialize_error_reporting
    import sentry_sdk
ModuleNotFoundError: No module named 'sentry_sdk'
```

**Comment by khalo-sa** [comment]
When does this happen? 

It's weird, because if you followed the documented steps you should end up with the same virtual environment like mine. I just checked, and in my conda env called "rasa-3.0.5" the package `sentry-sdk` version 1.3.1 is present, which is why I'm not seeing the error that you got.

Maybe it's worth trying one more time? So remove the created env first, then install again following the steps.

**Comment by rgstephens** [comment]
If fails on `rasa train`.  It's not related to Postgres. The package is present but still failing.  The docker build works.

**Comment by khalo-sa** [comment]
Works on my end. Would love to assist, but I have no idea how tbh.

![image](https://user-images.githubusercontent.com/14795990/152401703-5e1af8ac-deaa-41db-a3cf-f6cf5a357965.png)
